// @generated by protoc-gen-es v1.7.2
// @generated from file Protos/v1/article.proto (package article.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message article.v1.Article
 */
export declare class Article extends Message<Article> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string hero_image_alt = 4;
   */
  heroImageAlt: string;

  /**
   * @generated from field: string hero_image_url = 5;
   */
  heroImageUrl: string;

  /**
   * @generated from field: string cta_title = 6;
   */
  ctaTitle: string;

  /**
   * @generated from field: string cta_url = 7;
   */
  ctaUrl: string;

  constructor(data?: PartialMessage<Article>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "article.v1.Article";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Article;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Article;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Article;

  static equals(a: Article | PlainMessage<Article> | undefined, b: Article | PlainMessage<Article> | undefined): boolean;
}

/**
 * @generated from message article.v1.ListArticlesRequest
 */
export declare class ListArticlesRequest extends Message<ListArticlesRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  constructor(data?: PartialMessage<ListArticlesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "article.v1.ListArticlesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArticlesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArticlesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArticlesRequest;

  static equals(a: ListArticlesRequest | PlainMessage<ListArticlesRequest> | undefined, b: ListArticlesRequest | PlainMessage<ListArticlesRequest> | undefined): boolean;
}

/**
 * @generated from message article.v1.ListArticlesResponse
 */
export declare class ListArticlesResponse extends Message<ListArticlesResponse> {
  /**
   * @generated from field: repeated article.v1.Article articles = 1;
   */
  articles: Article[];

  constructor(data?: PartialMessage<ListArticlesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "article.v1.ListArticlesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArticlesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArticlesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArticlesResponse;

  static equals(a: ListArticlesResponse | PlainMessage<ListArticlesResponse> | undefined, b: ListArticlesResponse | PlainMessage<ListArticlesResponse> | undefined): boolean;
}

