// @generated by protoc-gen-connect-es v1.4.0
// @generated from file Protos/v1/article.proto (package article.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListArticlesRequest, ListArticlesResponse } from "./article_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Article service
 *
 * @generated from service article.v1.ArticleService
 */
export declare const ArticleService: {
  readonly typeName: "article.v1.ArticleService",
  readonly methods: {
    /**
     * List all articles
     *
     * @generated from rpc article.v1.ArticleService.ListArticles
     */
    readonly listArticles: {
      readonly name: "ListArticles",
      readonly I: typeof ListArticlesRequest,
      readonly O: typeof ListArticlesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

