// @generated by protoc-gen-es v1.7.2
// @generated from file Protos/v1/article.proto (package article.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message article.v1.Article
 */
export const Article = proto3.makeMessageType(
  "article.v1.Article",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "hero_image_alt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "hero_image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "cta_title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "cta_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message article.v1.ListArticlesRequest
 */
export const ListArticlesRequest = proto3.makeMessageType(
  "article.v1.ListArticlesRequest",
  () => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message article.v1.ListArticlesResponse
 */
export const ListArticlesResponse = proto3.makeMessageType(
  "article.v1.ListArticlesResponse",
  () => [
    { no: 1, name: "articles", kind: "message", T: Article, repeated: true },
  ],
);

