// @generated by protoc-gen-connect-es v1.4.0
// @generated from file Protos/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { VerifyUserRequest, VerifyUserResponse, WhoAmIRequest, WhoAmIResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Auth service
 *
 * @generated from service auth.v1.AuthService
 */
export const AuthService = {
  typeName: "auth.v1.AuthService",
  methods: {
    /**
     * Verify whether a user is a registered SSTAA member
     *
     * @generated from rpc auth.v1.AuthService.VerifyUser
     */
    verifyUser: {
      name: "VerifyUser",
      I: VerifyUserRequest,
      O: VerifyUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.WhoAmI
     */
    whoAmI: {
      name: "WhoAmI",
      I: WhoAmIRequest,
      O: WhoAmIResponse,
      kind: MethodKind.Unary,
    },
  }
};

