// @generated by protoc-gen-es v1.7.2
// @generated from file Protos/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message auth.v1.VerifyUserRequest
 */
export const VerifyUserRequest = proto3.makeMessageType(
  "auth.v1.VerifyUserRequest",
  () => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message auth.v1.VerifyUserResponse
 */
export const VerifyUserResponse = proto3.makeMessageType(
  "auth.v1.VerifyUserResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "linked", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message auth.v1.WhoAmIRequest
 */
export const WhoAmIRequest = proto3.makeMessageType(
  "auth.v1.WhoAmIRequest",
  [],
);

/**
 * @generated from message auth.v1.WhoAmIResponse
 */
export const WhoAmIResponse = proto3.makeMessageType(
  "auth.v1.WhoAmIResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

