// @generated by protoc-gen-connect-es v1.4.0
// @generated from file Protos/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { VerifyUserRequest, VerifyUserResponse, WhoAmIRequest, WhoAmIResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Auth service
 *
 * @generated from service auth.v1.AuthService
 */
export declare const AuthService: {
  readonly typeName: "auth.v1.AuthService",
  readonly methods: {
    /**
     * Verify whether a user is a registered SSTAA member
     *
     * @generated from rpc auth.v1.AuthService.VerifyUser
     */
    readonly verifyUser: {
      readonly name: "VerifyUser",
      readonly I: typeof VerifyUserRequest,
      readonly O: typeof VerifyUserResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.v1.AuthService.WhoAmI
     */
    readonly whoAmI: {
      readonly name: "WhoAmI",
      readonly I: typeof WhoAmIRequest,
      readonly O: typeof WhoAmIResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

