// @generated by protoc-gen-connect-es v1.4.0
// @generated from file Protos/v1/event.proto (package event.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddAttendeeRequest, BatchAddAttendeesRequest, CreateEventRequest, DeleteEventRequest, Event, GetAdmissionRequest, GetEventRequest, ListEventsRequest, ListEventsResponse, UpdateEventRequest } from "./event_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * Event service
 *
 * @generated from service event.v1.EventService
 */
export declare const EventService: {
  readonly typeName: "event.v1.EventService",
  readonly methods: {
    /**
     * @generated from rpc event.v1.EventService.ListEvents
     */
    readonly listEvents: {
      readonly name: "ListEvents",
      readonly I: typeof ListEventsRequest,
      readonly O: typeof ListEventsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.GetEvent
     */
    readonly getEvent: {
      readonly name: "GetEvent",
      readonly I: typeof GetEventRequest,
      readonly O: typeof Event,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Get an event by an admission ID
     *
     * @generated from rpc event.v1.EventService.GetAdmission
     */
    readonly getAdmission: {
      readonly name: "GetAdmission",
      readonly I: typeof GetAdmissionRequest,
      readonly O: typeof Event,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.CreateEvent
     */
    readonly createEvent: {
      readonly name: "CreateEvent",
      readonly I: typeof CreateEventRequest,
      readonly O: typeof Event,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.UpdateEvent
     */
    readonly updateEvent: {
      readonly name: "UpdateEvent",
      readonly I: typeof UpdateEventRequest,
      readonly O: typeof Event,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.DeleteEvent
     */
    readonly deleteEvent: {
      readonly name: "DeleteEvent",
      readonly I: typeof DeleteEventRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.AddAttendee
     */
    readonly addAttendee: {
      readonly name: "AddAttendee",
      readonly I: typeof AddAttendeeRequest,
      readonly O: typeof Event,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.BatchAddAttendees
     */
    readonly batchAddAttendees: {
      readonly name: "BatchAddAttendees",
      readonly I: typeof BatchAddAttendeesRequest,
      readonly O: typeof Event,
      readonly kind: MethodKind.Unary,
    },
  }
};

