// @generated by protoc-gen-connect-es v1.4.0
// @generated from file Protos/v1/event.proto (package event.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddAttendeeRequest, BatchAddAttendeesRequest, CreateEventRequest, DeleteEventRequest, Event, GetAdmissionRequest, GetEventRequest, ListEventsRequest, ListEventsResponse, UpdateEventRequest } from "./event_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * Event service
 *
 * @generated from service event.v1.EventService
 */
export const EventService = {
  typeName: "event.v1.EventService",
  methods: {
    /**
     * @generated from rpc event.v1.EventService.ListEvents
     */
    listEvents: {
      name: "ListEvents",
      I: ListEventsRequest,
      O: ListEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.GetEvent
     */
    getEvent: {
      name: "GetEvent",
      I: GetEventRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
    /**
     * Get an event by an admission ID
     *
     * @generated from rpc event.v1.EventService.GetAdmission
     */
    getAdmission: {
      name: "GetAdmission",
      I: GetAdmissionRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.CreateEvent
     */
    createEvent: {
      name: "CreateEvent",
      I: CreateEventRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.UpdateEvent
     */
    updateEvent: {
      name: "UpdateEvent",
      I: UpdateEventRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.DeleteEvent
     */
    deleteEvent: {
      name: "DeleteEvent",
      I: DeleteEventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.AddAttendee
     */
    addAttendee: {
      name: "AddAttendee",
      I: AddAttendeeRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc event.v1.EventService.BatchAddAttendees
     */
    batchAddAttendees: {
      name: "BatchAddAttendees",
      I: BatchAddAttendeesRequest,
      O: Event,
      kind: MethodKind.Unary,
    },
  }
};

