// @generated by protoc-gen-es v1.7.2
// @generated from file Protos/v1/event.proto (package event.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FieldMask, proto3, Timestamp } from "@bufbuild/protobuf";
import { User } from "./user_pb.js";

/**
 * @generated from message event.v1.Event
 */
export const Event = proto3.makeMessageType(
  "event.v1.Event",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "location", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "badgeImage", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "start_date_time", kind: "message", T: Timestamp },
    { no: 7, name: "end_date_time", kind: "message", T: Timestamp },
    { no: 8, name: "attendees", kind: "message", T: EventUser, repeated: true },
  ],
);

/**
 * @generated from message event.v1.EventUser
 */
export const EventUser = proto3.makeMessageType(
  "event.v1.EventUser",
  () => [
    { no: 1, name: "admission_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user", kind: "message", T: User },
  ],
);

/**
 * @generated from message event.v1.ListEventsRequest
 */
export const ListEventsRequest = proto3.makeMessageType(
  "event.v1.ListEventsRequest",
  () => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message event.v1.ListEventsResponse
 */
export const ListEventsResponse = proto3.makeMessageType(
  "event.v1.ListEventsResponse",
  () => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
  ],
);

/**
 * @generated from message event.v1.GetEventRequest
 */
export const GetEventRequest = proto3.makeMessageType(
  "event.v1.GetEventRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message event.v1.GetAdmissionRequest
 */
export const GetAdmissionRequest = proto3.makeMessageType(
  "event.v1.GetAdmissionRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message event.v1.CreateEventRequest
 */
export const CreateEventRequest = proto3.makeMessageType(
  "event.v1.CreateEventRequest",
  () => [
    { no: 1, name: "event", kind: "message", T: Event },
  ],
);

/**
 * @generated from message event.v1.UpdateEventRequest
 */
export const UpdateEventRequest = proto3.makeMessageType(
  "event.v1.UpdateEventRequest",
  () => [
    { no: 1, name: "event", kind: "message", T: Event },
    { no: 2, name: "update_mask", kind: "message", T: FieldMask },
  ],
);

/**
 * @generated from message event.v1.DeleteEventRequest
 */
export const DeleteEventRequest = proto3.makeMessageType(
  "event.v1.DeleteEventRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message event.v1.AddAttendeeRequest
 */
export const AddAttendeeRequest = proto3.makeMessageType(
  "event.v1.AddAttendeeRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message event.v1.BatchAddAttendeesRequest
 */
export const BatchAddAttendeesRequest = proto3.makeMessageType(
  "event.v1.BatchAddAttendeesRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "users", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

