// @generated by protoc-gen-connect-es v1.4.0
// @generated from file Protos/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchCreateUsersRequest, BatchCreateUsersResponse, BindUserRequest, CreateUserRequest, DeleteUserRequest, GetUserRequest, ListUsersRequest, ListUsersResponse, UpdateUserRequest, User } from "./user_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * User service
 *
 * @generated from service user.v1.UserService
 */
export declare const UserService: {
  readonly typeName: "user.v1.UserService",
  readonly methods: {
    /**
     * List all users, restricted to EXCO
     *
     * @generated from rpc user.v1.UserService.ListUsers
     */
    readonly listUsers: {
      readonly name: "ListUsers",
      readonly I: typeof ListUsersRequest,
      readonly O: typeof ListUsersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Get user information, restricted to authenticated users
     *
     * @generated from rpc user.v1.UserService.GetUser
     */
    readonly getUser: {
      readonly name: "GetUser",
      readonly I: typeof GetUserRequest,
      readonly O: typeof User,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Bind user to a Firebase ID. Although this can also be done in the UpdateUser route, due to the different 
     * permission requirement for updating FirebaseId, it would introduce a partial success state for the endpoint (where
     * only the FirebaseId is updated of all fields provided in the UpdateMask). Therefore, a separate route exists for
     * this specific use case. This route should be called by end-users only (not admins) as it will bind the user ID 
     * provided to the current authenticated user.
     *
     * @generated from rpc user.v1.UserService.BindUser
     */
    readonly bindUser: {
      readonly name: "BindUser",
      readonly I: typeof BindUserRequest,
      readonly O: typeof User,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Create users
     *
     * @generated from rpc user.v1.UserService.CreateUser
     */
    readonly createUser: {
      readonly name: "CreateUser",
      readonly I: typeof CreateUserRequest,
      readonly O: typeof User,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Batch create users
     *
     * @generated from rpc user.v1.UserService.BatchCreateUsers
     */
    readonly batchCreateUsers: {
      readonly name: "BatchCreateUsers",
      readonly I: typeof BatchCreateUsersRequest,
      readonly O: typeof BatchCreateUsersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Update user
     *
     * @generated from rpc user.v1.UserService.UpdateUser
     */
    readonly updateUser: {
      readonly name: "UpdateUser",
      readonly I: typeof UpdateUserRequest,
      readonly O: typeof User,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Delete user
     *
     * @generated from rpc user.v1.UserService.DeleteUser
     */
    readonly deleteUser: {
      readonly name: "DeleteUser",
      readonly I: typeof DeleteUserRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

