// @generated by protoc-gen-es v1.7.2
// @generated from file Protos/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, FieldMask, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum user.v1.Membership
 */
export declare enum Membership {
  /**
   * @generated from enum value: Exco = 0;
   */
  Exco = 0,

  /**
   * @generated from enum value: Associate = 1;
   */
  Associate = 1,

  /**
   * @generated from enum value: Affiliate = 2;
   */
  Affiliate = 2,

  /**
   * @generated from enum value: Ordinary = 3;
   */
  Ordinary = 3,

  /**
   * @generated from enum value: Revoked = 4;
   */
  Revoked = 4,
}

/**
 * @generated from enum user.v1.ServiceAccountType
 */
export declare enum ServiceAccountType {
  /**
   * @generated from enum value: GuardHouse = 0;
   */
  GuardHouse = 0,
}

/**
 * @generated from message user.v1.User
 */
export declare class User extends Message<User> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string firebase_id = 4;
   */
  firebaseId: string;

  /**
   * @generated from oneof user.v1.User.user_type
   */
  userType: {
    /**
     * @generated from field: user.v1.Member member = 100;
     */
    value: Member;
    case: "member";
  } | {
    /**
     * @generated from field: user.v1.Employee employee = 101;
     */
    value: Employee;
    case: "employee";
  } | {
    /**
     * @generated from field: user.v1.ServiceAccount service_account = 102;
     */
    value: ServiceAccount;
    case: "serviceAccount";
  } | {
    /**
     * @generated from field: user.v1.SystemAdmin system_admin = 103;
     */
    value: SystemAdmin;
    case: "systemAdmin";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<User>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.User";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User;

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean;
}

/**
 * @generated from message user.v1.Member
 */
export declare class Member extends Message<Member> {
  /**
   * @generated from field: user.v1.Membership membership = 1;
   */
  membership: Membership;

  /**
   * @generated from field: string member_id = 2;
   */
  memberId: string;

  /**
   * @generated from oneof user.v1.Member.member_type
   */
  memberType: {
    /**
     * @generated from field: user.v1.AlumniMember alumni_member = 3;
     */
    value: AlumniMember;
    case: "alumniMember";
  } | {
    /**
     * @generated from field: user.v1.EmployeeMember employee_member = 4;
     */
    value: EmployeeMember;
    case: "employeeMember";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Member>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.Member";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Member;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Member;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Member;

  static equals(a: Member | PlainMessage<Member> | undefined, b: Member | PlainMessage<Member> | undefined): boolean;
}

/**
 * @generated from message user.v1.AlumniMember
 */
export declare class AlumniMember extends Message<AlumniMember> {
  /**
   * If a member is an associate and have never graduated from SST, this field will be empty.
   *
   * @generated from field: optional int32 graduation_year = 1;
   */
  graduationYear?: number;

  constructor(data?: PartialMessage<AlumniMember>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.AlumniMember";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AlumniMember;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AlumniMember;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AlumniMember;

  static equals(a: AlumniMember | PlainMessage<AlumniMember> | undefined, b: AlumniMember | PlainMessage<AlumniMember> | undefined): boolean;
}

/**
 * @generated from message user.v1.EmployeeMember
 */
export declare class EmployeeMember extends Message<EmployeeMember> {
  /**
   * If a member was an ex-student of SST, this field will contain their graduation year.
   *
   * @generated from field: optional int32 graduation_year = 1;
   */
  graduationYear?: number;

  constructor(data?: PartialMessage<EmployeeMember>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.EmployeeMember";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmployeeMember;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmployeeMember;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmployeeMember;

  static equals(a: EmployeeMember | PlainMessage<EmployeeMember> | undefined, b: EmployeeMember | PlainMessage<EmployeeMember> | undefined): boolean;
}

/**
 * @generated from message user.v1.ServiceAccount
 */
export declare class ServiceAccount extends Message<ServiceAccount> {
  /**
   * @generated from field: user.v1.ServiceAccountType service_account_type = 1;
   */
  serviceAccountType: ServiceAccountType;

  constructor(data?: PartialMessage<ServiceAccount>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.ServiceAccount";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceAccount;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceAccount;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceAccount;

  static equals(a: ServiceAccount | PlainMessage<ServiceAccount> | undefined, b: ServiceAccount | PlainMessage<ServiceAccount> | undefined): boolean;
}

/**
 * @generated from message user.v1.SystemAdmin
 */
export declare class SystemAdmin extends Message<SystemAdmin> {
  constructor(data?: PartialMessage<SystemAdmin>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.SystemAdmin";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SystemAdmin;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SystemAdmin;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SystemAdmin;

  static equals(a: SystemAdmin | PlainMessage<SystemAdmin> | undefined, b: SystemAdmin | PlainMessage<SystemAdmin> | undefined): boolean;
}

/**
 * @generated from message user.v1.Employee
 */
export declare class Employee extends Message<Employee> {
  constructor(data?: PartialMessage<Employee>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.Employee";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Employee;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Employee;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Employee;

  static equals(a: Employee | PlainMessage<Employee> | undefined, b: Employee | PlainMessage<Employee> | undefined): boolean;
}

/**
 * @generated from message user.v1.ListUsersRequest
 */
export declare class ListUsersRequest extends Message<ListUsersRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  constructor(data?: PartialMessage<ListUsersRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.ListUsersRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUsersRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUsersRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUsersRequest;

  static equals(a: ListUsersRequest | PlainMessage<ListUsersRequest> | undefined, b: ListUsersRequest | PlainMessage<ListUsersRequest> | undefined): boolean;
}

/**
 * @generated from message user.v1.ListUsersResponse
 */
export declare class ListUsersResponse extends Message<ListUsersResponse> {
  /**
   * @generated from field: repeated user.v1.User users = 1;
   */
  users: User[];

  constructor(data?: PartialMessage<ListUsersResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.ListUsersResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUsersResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUsersResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUsersResponse;

  static equals(a: ListUsersResponse | PlainMessage<ListUsersResponse> | undefined, b: ListUsersResponse | PlainMessage<ListUsersResponse> | undefined): boolean;
}

/**
 * @generated from message user.v1.GetUserRequest
 */
export declare class GetUserRequest extends Message<GetUserRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<GetUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.GetUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserRequest;

  static equals(a: GetUserRequest | PlainMessage<GetUserRequest> | undefined, b: GetUserRequest | PlainMessage<GetUserRequest> | undefined): boolean;
}

/**
 * @generated from message user.v1.BindUserRequest
 */
export declare class BindUserRequest extends Message<BindUserRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<BindUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.BindUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BindUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BindUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BindUserRequest;

  static equals(a: BindUserRequest | PlainMessage<BindUserRequest> | undefined, b: BindUserRequest | PlainMessage<BindUserRequest> | undefined): boolean;
}

/**
 * @generated from message user.v1.CreateUserRequest
 */
export declare class CreateUserRequest extends Message<CreateUserRequest> {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;

  constructor(data?: PartialMessage<CreateUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.CreateUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateUserRequest;

  static equals(a: CreateUserRequest | PlainMessage<CreateUserRequest> | undefined, b: CreateUserRequest | PlainMessage<CreateUserRequest> | undefined): boolean;
}

/**
 * @generated from message user.v1.BatchCreateUsersRequest
 */
export declare class BatchCreateUsersRequest extends Message<BatchCreateUsersRequest> {
  /**
   * @generated from field: repeated user.v1.CreateUserRequest requests = 1;
   */
  requests: CreateUserRequest[];

  constructor(data?: PartialMessage<BatchCreateUsersRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.BatchCreateUsersRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchCreateUsersRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchCreateUsersRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchCreateUsersRequest;

  static equals(a: BatchCreateUsersRequest | PlainMessage<BatchCreateUsersRequest> | undefined, b: BatchCreateUsersRequest | PlainMessage<BatchCreateUsersRequest> | undefined): boolean;
}

/**
 * @generated from message user.v1.BatchCreateUsersResponse
 */
export declare class BatchCreateUsersResponse extends Message<BatchCreateUsersResponse> {
  /**
   * @generated from field: repeated user.v1.User users = 1;
   */
  users: User[];

  constructor(data?: PartialMessage<BatchCreateUsersResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.BatchCreateUsersResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchCreateUsersResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchCreateUsersResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchCreateUsersResponse;

  static equals(a: BatchCreateUsersResponse | PlainMessage<BatchCreateUsersResponse> | undefined, b: BatchCreateUsersResponse | PlainMessage<BatchCreateUsersResponse> | undefined): boolean;
}

/**
 * @generated from message user.v1.UpdateUserRequest
 */
export declare class UpdateUserRequest extends Message<UpdateUserRequest> {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;

  constructor(data?: PartialMessage<UpdateUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.UpdateUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserRequest;

  static equals(a: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined, b: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined): boolean;
}

/**
 * @generated from message user.v1.DeleteUserRequest
 */
export declare class DeleteUserRequest extends Message<DeleteUserRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<DeleteUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "user.v1.DeleteUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteUserRequest;

  static equals(a: DeleteUserRequest | PlainMessage<DeleteUserRequest> | undefined, b: DeleteUserRequest | PlainMessage<DeleteUserRequest> | undefined): boolean;
}

